// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

RWTexture2D<float4> Result;
RWStructuredBuffer<float3> positionBuffer;
float positionCount;
float2 size;

float Metaball(float3 uv, float3 pos, float radius){
    return radius/dot(uv-pos,uv-pos);
}


[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 uv = float2(id.x / size.x, id.y / size.y);
    float4 color = float4(0, 0, 0, 1);
    float metaballs = 0;

    for(int i = 0; i < positionCount; i++){
        metaballs += Metaball(float3(uv, 0), positionBuffer[i], 0.02);
    }
    color.x = metaballs;

    Result[id.xy] = color;
}
